-- MySQL Script generated by MySQL Workbench
-- Thu Nov 29 11:53:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema p1710336
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema p1710336
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p1710336` DEFAULT CHARACTER SET utf8 ;
USE `p1710336` ;

-- -----------------------------------------------------
-- Table `p1710336`.`Cartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p1710336`.`Cartes` (
  `idC` INT(11) NOT NULL,
  `codeC` VARCHAR(45) NOT NULL,
  `nomC` VARCHAR(255) NOT NULL,
  `contenu` MEDIUMBLOB NULL,
  PRIMARY KEY (`idC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p1710336`.`Partie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p1710336`.`Partie` (
  `idPartie` INT(11) NOT NULL AUTO_INCREMENT,
  `vainqueurPartie` VARCHAR(45) NULL,
  `nbManches` INT(2) NULL,
  `debutPartie` DATETIME NULL,
  `finPartie` DATETIME NULL,
  PRIMARY KEY (`idPartie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p1710336`.`Jeu_Carte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p1710336`.`Jeu_Carte` (
  `idJeu` INT NOT NULL,
  `Cartes_idC` INT(11) NOT NULL,
  `Partie_idP` INT NOT NULL,
  PRIMARY KEY (`idJeu`, `Cartes_idC`, `Partie_idP`),
  INDEX `fk_JeuDeCarte_Cartes_idx` (`Cartes_idC` ASC),
  INDEX `fk_JeuDeCarte_Partie1_idx` (`Partie_idP` ASC),
  CONSTRAINT `fk_JeuDeCarte_Cartes`
    FOREIGN KEY (`Cartes_idC`)
    REFERENCES `p1710336`.`Cartes` (`idC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JeuDeCarte_Partie1`
    FOREIGN KEY (`Partie_idP`)
    REFERENCES `p1710336`.`Partie` (`idPartie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p1710336`.`Manche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p1710336`.`Manche` (
  `idManche` INT NOT NULL AUTO_INCREMENT,
  `debutManche` DATETIME NULL,
  `finManche` DATETIME NULL,
  `vainqueurManche` VARCHAR(45) NULL,
  `ScoreJ1` INT(5) NULL,
  `ScoreJ2` INT(5) NULL,
  `Partie_idPartie` INT(11) NOT NULL,
  PRIMARY KEY (`idManche`, `Partie_idPartie`),
  INDEX `fk_Manche_Partie1_idx` (`Partie_idPartie` ASC),
  CONSTRAINT `fk_Manche_Partie1`
    FOREIGN KEY (`Partie_idPartie`)
    REFERENCES `p1710336`.`Partie` (`idPartie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p1710336`.`Tour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p1710336`.`Tour` (
  `idTour` INT NOT NULL AUTO_INCREMENT,
  `scoreTotal` INT(5) NULL,
  `Manche_idManche` INT NOT NULL,
  `Manche_Partie_idPartie` INT(11) NOT NULL,
  PRIMARY KEY (`idTour`, `Manche_idManche`, `Manche_Partie_idPartie`),
  INDEX `fk_Tour_Manche1_idx` (`Manche_idManche` ASC, `Manche_Partie_idPartie` ASC),
  CONSTRAINT `fk_Tour_Manche1`
    FOREIGN KEY (`Manche_idManche` , `Manche_Partie_idPartie`)
    REFERENCES `p1710336`.`Manche` (`idManche` , `Partie_idPartie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p1710336`.`Joueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p1710336`.`Joueur` (
  `idJoueur` INT NOT NULL AUTO_INCREMENT,
  `couleur` VARCHAR(45) NULL,
  PRIMARY KEY (`idJoueur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p1710336`.`Action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p1710336`.`Action` (
  `idAction` INT NOT NULL,
  `nomAction` VARCHAR(45) NULL,
  `Tour_idTour` INT NOT NULL,
  `Tour_Manche_idManche` INT NOT NULL,
  `Tour_Manche_Partie_idPartie` INT(11) NOT NULL,
  `Joueur_idJoueur` INT NOT NULL,
  PRIMARY KEY (`idAction`, `Tour_idTour`, `Tour_Manche_idManche`, `Tour_Manche_Partie_idPartie`),
  INDEX `fk_Action_Tour1_idx` (`Tour_idTour` ASC, `Tour_Manche_idManche` ASC, `Tour_Manche_Partie_idPartie` ASC),
  INDEX `fk_Action_Joueur1_idx` (`Joueur_idJoueur` ASC),
  CONSTRAINT `fk_Action_Tour1`
    FOREIGN KEY (`Tour_idTour` , `Tour_Manche_idManche` , `Tour_Manche_Partie_idPartie`)
    REFERENCES `p1710336`.`Tour` (`idTour` , `Manche_idManche` , `Manche_Partie_idPartie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Action_Joueur1`
    FOREIGN KEY (`Joueur_idJoueur`)
    REFERENCES `p1710336`.`Joueur` (`idJoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p1710336`.`Humain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p1710336`.`Humain` (
  `pseudo` VARCHAR(20) NOT NULL,
  `nomJ` VARCHAR(45) NULL,
  `prenomJ` VARCHAR(45) NULL,
  `dateCreationCompte` DATETIME NULL,
  `val_hachage` VARCHAR(45) NULL,
  `Joueur_idJoueur` INT NOT NULL,
  PRIMARY KEY (`pseudo`, `Joueur_idJoueur`),
  INDEX `fk_Joueur_H_Joueur1_idx` (`Joueur_idJoueur` ASC),
  CONSTRAINT `fk_Joueur_H_Joueur1`
    FOREIGN KEY (`Joueur_idJoueur`)
    REFERENCES `p1710336`.`Joueur` (`idJoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p1710336`.`IA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p1710336`.`IA` (
  `strategie` VARCHAR(20) NOT NULL,
  `chanceCogner` INT(2) NULL,
  `chancePiocher` INT(2) NULL,
  `chanceDefausser` INT(2) NULL,
  `Joueur_idJoueur` INT NOT NULL,
  PRIMARY KEY (`strategie`, `Joueur_idJoueur`),
  INDEX `fk_IA_Joueur1_idx` (`Joueur_idJoueur` ASC),
  CONSTRAINT `fk_IA_Joueur1`
    FOREIGN KEY (`Joueur_idJoueur`)
    REFERENCES `p1710336`.`Joueur` (`idJoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p1710336`.`joue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p1710336`.`joue` (
  `Partie_idPartie` INT(11) NOT NULL AUTO_INCREMENT,
  `Joueur_idJoueur` INT NOT NULL,
  PRIMARY KEY (`Partie_idPartie`, `Joueur_idJoueur`),
  INDEX `fk_joue_Joueur1_idx` (`Joueur_idJoueur` ASC),
  CONSTRAINT `fk_joue_Partie1`
    FOREIGN KEY (`Partie_idPartie`)
    REFERENCES `p1710336`.`Partie` (`idPartie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joue_Joueur1`
    FOREIGN KEY (`Joueur_idJoueur`)
    REFERENCES `p1710336`.`Joueur` (`idJoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
